Reduce the AWS artifact upload concurrency and increase retries (#1041)
Attempting to resolve release failures

```
     Running `target/release/pythonbuild upload-mirror-distributions --dist dist --datetime 20260324T0736 --tag 20260324 --bucket *** --prefix github/python-build-standalone/releases/download/20260324/`
found all 852 release artifacts
uploading cpython-3.10.20-aarch64-apple-darwin-debug-20260324T0736.tar.zst -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-apple-darwin-debug-full.tar.zst
uploading cpython-3.10.20-aarch64-apple-darwin-install_only-20260324T0736.tar.gz -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-apple-darwin-install_only.tar.gz
uploading cpython-3.10.20-aarch64-apple-darwin-install_only_stripped-20260324T0736.tar.gz -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-apple-darwin-install_only_stripped.tar.gz
uploading cpython-3.10.20-aarch64-apple-darwin-pgo+lto-20260324T0736.tar.zst -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-apple-darwin-pgo+lto-full.tar.zst
uploading cpython-3.10.20-aarch64-unknown-linux-gnu-debug-20260324T0736.tar.zst -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-unknown-linux-gnu-debug-full.tar.zst
uploading cpython-3.10.20-aarch64-unknown-linux-gnu-install_only-20260324T0736.tar.gz -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-unknown-linux-gnu-install_only.tar.gz
uploading cpython-3.10.20-aarch64-unknown-linux-gnu-install_only_stripped-20260324T0736.tar.gz -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-unknown-linux-gnu-install_only_stripped.tar.gz
uploading cpython-3.10.20-aarch64-unknown-linux-gnu-pgo+lto-20260324T0736.tar.zst -> s3://***/github/python-build-standalone/releases/download/20260324/cpython-3.10.20+20260324-aarch64-unknown-linux-gnu-pgo+lto-full.tar.zst
Error: dispatch failure

Caused by:
    0: io error
    1: client error (SendRequest)
    2: connection error
    3: Connection reset by peer (os error 104)
error: Recipe `release-upload-mirror` failed with exit code 1
```